sudo: false
language: java
jdk:
  - openjdk7
  - oraclejdk8
branches:
  only:
    - master

notifications:
  recipients:
    - elaatifi@gmail.com
    - matt.deboer@gmail.com
  email:
    on_success: always
    on_failure: always
